
```{r}
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")
library(tidyverse)
library(missRanger)

```

load
```{r}
df <- readRDS("data/dat.rds")
head(df)
colnames(df)
dim(df)
length(unique(df$id))
# Y:youth; A: adult
# ed: ED
# SH: suicide
# OTH: non-suicide death
with(df, tapply(SHYed, list(statefips, year), mean))
with(df, tapply(SHY, list(statefips, year), mean))
with(df, tapply(OTHERYed, list(statefips, year), mean))
with(df, tapply(OTHERY, list(statefips, year), mean))

with(df, tapply(SHYed / OTHERYed, list(statefips, year), mean)) %>% round(3)
with(df, tapply(SHY / OTHERY, list(statefips, year), mean)) %>% round(3)

colnames(df)
summary(df$long)

```

#===============================================================================
#sort data so it agrees with GS
```{r}
library(spdep)
load("data/hmap")
nb <- poly2nb(hmap)

length(unique(attributes(nb)$region.id))
length(unique(df$id))

i <- 1:length(attributes(nb)$region.id);
names(i) <-  attributes(nb)$region.id
cbind(i[paste(df$id)], as.numeric(as.factor(df$id)))[1:20, ]

df$i <-  i[paste(df$id)]
df$t  <- df$yr
df <- df[order(df$i, df$t),]

head(df)
summary(df$i)
length(unique(df$i))
max(df$i)
```

```{r}
#add lat an lon
load("data/hmap")
coord <- as.data.frame(sp::coordinates(hmap))
colnames(coord) <- c("lon", "lat")
coord$id <- as.integer(rownames(coord))
df <- left_join(df, coord, by = "id")
dim(df)
df <- arrange(df, i, t)

table(df$i == as.numeric(factor(df$i)))


colnames(df)
# the dataset is prepare to analyze hospital activity
# replacing here by suicide
df <- df %>%
  mutate(
    y = S1024
    , y25 = S25
    , y0_25 = ifelse(as.numeric(year >= yr1), NA, y25)
    , y0 = ifelse(as.numeric(year >= yr1), NA, y)
    , start_year = yr1
    , n = P1024
    , n25 = P25
    , E = sum(y) / sum(n) * n
    , time = year - 1998
    , SMR = y / E
    , st = as.factor(statefips)
    , urb = as.factor(urb13)
    , fid = as.factor(i)
    , fyr = as.factor(year)
    , across(where(is.character), as.factor)
    , fip = COUNTYFIPS
    , long = long
  )

colnames(df)
dt <- df %>%
  select(fip, i, year, y, y25, n, n25, y0, y0_25
    , start_year
    , urb
    , st, HSA_name, region,  division
    , TribalStatus, AIAN
    , urb
    , lon, lat
    , uemp, pov, mhinc
    , long
  )


dt %>% summary
dt <- dt %>%
  mutate(start_year = if_else(start_year == 9999, Inf, start_year)
    , event_time = year - start_year
  )

head(dt[is.na(dt$uemp), ])
dt[dt$i %in% dt$i[is.na(dt$uemp)], ]
```


#1 county missin coviariates 2 years
```{r}
dt[, c("AIAN", "uemp", "pov", "mhinc")] <- dt %>%
  missRanger %>%
  select(AIAN, uemp, pov, mhinc)

dt[dt$fip == "46113", ]

saveRDS(dt, "data/compact_dt.rds")
```