```{r}
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")

library(parallel)
library(tidyverse)

#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
library(data.table)

library(rpart)
```

Select data
(compact is created in 3.0, basically a subset)
```{r}
dt <-  readRDS("data/compact_dt.rds")
dt0 <-  filter(dt, year < start_year)
dim(dt0)

cor(dt0$Y / dt0$n, dt0$y25 / dt0$n25, method = "spearman")
tapply(dt0$y25 / dt0$n25 * 10^5, dt0$urb, mean)
tapply(dt0$Y / dt0$n * 10^5, dt0$urb, mean)

```

```{r}
dt0 %>% shuffle_start("mar") %>% with(., prop.table(table(is.na(y0))))
dt0 %>% shuffle_start("mcar") %>% with(., prop.table(table(is.na(y0))))

dt0 %>% shuffle_start("mar") %>% add_avg %>%
  group_by(i, start_year) %>%
  reframe(a = mean(mi_y0 + mi_y25) / n) %>%
  with(., cor(start_year, a, method = "spearman"))

summary(dt0)
dt0 %>% shuffle_start("mar") %>% add_avg %>%
  with(., cor(start_year, n, method = "spearman"))

dt0 %>% shuffle_start("mar") %>% add_avg %>%
  with(., tapply(start_year, urb, median))



dt0 %>% shuffle_start("mcar") %>% add_avg %>%
  with(., tapply(mi_y0, is.na(y0), mean))

#dt0 %>% shuffle_start("mar") %>% add_avg %>% summary
```

placebo dataset with 
```{r}

#forest
set.seed(0203)
placebo_dt <- mclapply(1:80, \(x) {
  dt0 %>%
    shuffle_start("mar") %>%
    add_avg %>%
    impute_forest(200, k = 1,  min_bucket = 7, max_depth = 30)
}, mc.cores = 20) %>%
  bind_rows(.id = "replication")

placebo_dt %>%
  group_by(replication) %>%
  filter(is.na(y0)) %>%
  score0 %>% apply(2, \(x) mean(as.numeric(x)))

saveRDS(placebo_dt, "data/placebo_dt_mar_n.rds")
```




