

```{r}
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")
library(data.table)
library(tidyverse)
library(parallel)
#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)


library(INLA)
library(fixest)
library(parallel)
```

DATA
```{r}
placebo_dt <- readRDS("data/placebo_dt_0125.rds")
load("data/W")
rownames(W) <- NULL
```

```{r}
filter(placebo_dt, replication == 2) %>%
  with(., tapply(year - start_year, urb, median))

```

Inferece for forest
```{r}
#forest
#set.seed(0203)
#forest_fit <- mclapply(1:400, \(r) {
#  filter(placebo_dt, replication == r) %>%
#    inferece_forest(nboot = 200)
#}, mc.cores = 18) %>%
#  bind_rows


#forest_fit$method <- "forest"

#saveRDS(forest_fit, "data/forest_fit.rds")
```


#ME
with predictor as offset
```{r}
# mutate(m_yr = mean(ifelse(is.na(y0), scale(year), NA), na.rm = TRUE))
#head(placebo_dt$y0_hat)

t0 <- Sys.time()
set.seed(0203)
fm <- formula(y0 ~ offset(log(y0_hat)) - 1 + (1 | i))
#filter(placebo_dt, replication == 1) %>% fit_me(2)

mex_fit <- mclapply(1:400, \(r) {
  filter(placebo_dt, replication == r) %>%
    fit_me
}, mc.cores = 20) %>%
  bind_rows
t1 <- Sys.time()
print(t1 - t0)
mex_fit$method <- "mex"
saveRDS(mex_fit, "data/mex_fit.rds")
```

AR(1)
```{r}
t0 <- Sys.time()
set.seed(0203)
arx_fit <- mclapply(1:400, \(r) {
  filter(placebo_dt, replication == r) %>%
    fit_arx
}, mc.cores = 20) %>%
  bind_rows
t1 <- Sys.time()
print(t1 - t0)

saveRDS(arx_fit, "data/arx_fit.rds")
```

#spatio temporal x
```{r}
t0 <- Sys.time()
set.seed(0203)
spx_fit <- mclapply(1:400, \(r) {
  filter(placebo_dt, replication == r) %>%
    fit_spx
}, mc.cores = 20) %>%
  bind_rows
t1 <- Sys.time()
print(t1 - t0)

saveRDS(spx_fit, "data/spx_fit.rds")
```


#Fixed effects
```{r}
#filter(placebo_dt, replication == 1) %>% impute_fe
#filter(placebo_dt, replication == 1) %>% boot_fe(impute_fe, 5)

t0 <- Sys.time()
set.seed(0203)
fm <- formula(y0 ~ 1 | i + year)
twfe_fit <- mclapply(1:400, \(r) {
  filter(placebo_dt, replication == r) %>%
    fit_fe(200)
}, mc.cores = 20) %>%
  bind_rows
t1 <- Sys.time()
print(t1 - t0)
twfe_fit$method <- "twfe"
saveRDS(twfe_fit, "data/twfe_fit.rds")

# this is alrread a CRE model
# we are intrest in the effect of intervention,
# worried about heterogeneity
# so we include a cluster level average of the covariate (which is the same as the cohort indicator)

t0 <- Sys.time()
set.seed(0203)
fm <- formula(y0 ~ 1 | start_year + year)
etwfe_fit <- mclapply(1:400, \(r) {
  filter(placebo_dt, replication == r) %>%
    fit_fe(200)
}, mc.cores = 20) %>%
  bind_rows
t1 <- Sys.time()
print(t1 - t0)
etwfe_fit$method <- "etwfe"
saveRDS(etwfe_fit, "data/etwfe_fit.rds")
```

#-----------------------------------------------------------#

```{r}
.graph <- W_est(.data, W)
.data <- filter(placebo_dt, replication == 1)
.data$time <- as.numeric(factor(.data$year))
model <- inla(y0 ~ offset(log(y0_hat))  - 1
  + f(i, model = "besagproper2", graph = .graph
    , group = time, control.group = list(model = "ar1")
  )
  , family = "poisson"
  , data = .data
  , control.predictor = list(link = 1)
  , control.compute = list(dic = TRUE, cpo = TRUE, waic = TRUE
    , config = TRUE
  )
)
summary(model)


```


ME inla
```{r}
t0 <- Sys.time()
set.seed(0203)
me_inla_fit <- mclapply(1:400, \(r) {
  filter(placebo_dt, replication == r) %>%
    fit_me_inla
}, mc.cores = 20) %>%
  bind_rows
t1 <- Sys.time()
print(t1 - t0)
me_inla_fit$method <- "me_inla"

saveRDS(me_inla_fit, "data/fit_me_inla.rds")
```