```{r}
library(data.table)
library(tidyverse)
library(parallel)
options(digitis = 3)
options(scipen = 10^5) 
options(help_type = "html")

#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)


library(gt)
```


```{r}
ae <- \(y, y0) abs(y - y0)
se <- \(y, y0) (y - y0)^2

#coverage
cvg <- \(y, l, u) as.numeric(l <= y & y <= u)

#interval score 
intv <- \(y, l, u, α = .05) {
  (u - l) + 2 / α * (l - y) * (y < l) + 2 / α * (y - u) * (y > u)
}


#Poisson deviance
d2 <- \(y, y0) {
  ifelse(y > 0
    , 2 * (y * log(y / y0) + y0 - y)
    , 2 * y0
  )
}

#Dawid–Sebastiani score
ds <- \(y, y0, y0_sd) {
  sigpred <- sqrt(y0 + y0_sd^2)
  ((y - y0) / sigpred) ^ 2 + 2 * log(sigpred)
}

#Dawid–Sebastiani score
#depedns only on mean and SE (or poserior SD)
#*** Becouse the true att is zero att = bias
score <- \(m) {
  m %>%
    mutate(
      , d = Y - y0_hat
      , ae = ae(Y, y0_hat)
      , se = se(Y, y0_hat)
      , d2 = d2(Y, y0_hat)
      , lns = log(y0_pi)
      , ds = ds(Y, y0_hat, y0_sd)
      , cvg = cvg(Y, y0_lower, y0_upper)
      , intv = intv(Y, y0_lower, y0_upper)
      , sigpred = y0_hat + y0_sd^2
    ) %>%
    reframe(
      across(c(d, ae, se, d2, ds, lns, cvg, intv, sigpred)
        , \(x) mean(x, na.rm = TRUE)
      )
      , se = sqrt(se)
      , sigpred = sqrt(sigpred)
      , pcor = cor(Y, y0_hat, use = "complete.obs")
      , scor = cor(Y, y0_hat, method = "spearman", use = "complete.obs")
    )
}

score0 <- \(m) {
  m %>%
    mutate(
      , d = Y - y0_hat
      , ae = ae(Y, y0_hat)
      , se = se(Y, y0_hat)
      , d2 = d2(Y, y0_hat)
    ) %>%
    reframe(
      across(c(d, ae, se, d2)
        , \(x) mean(x, na.rm = TRUE)
      )
      , se = sqrt(se)
      , pcor = cor(Y, y0_hat, use = "complete.obs")
      , scor = cor(Y, y0_hat, method = "spearman", use = "complete.obs")
    )
}


```

```{r}
head(fits)
table(is.na(fits$Y0))

forest_fit <- readRDS("data/forest_fit.rds")
mex_fit <- readRDS("data/mex_fit.rds")
spx_fit <- readRDS("data/spx_fit.rds")
arx_fit <- readRDS("data/arx_fit.rds")
#spwe_fit <- readRDS("data/spwe_fit.rds")
#me_fit <- readRDS("data/me_fit.rds")
#me_inla_fit <- readRDS("data/me_inla_fit.rds")
twfe_fit <- readRDS("data/twfe_fit.rds")
etwfe_fit <- readRDS("data/etwfe_fit.rds")

fits <- list(forest_fit, mex_fit, arx_fit, spx_fit, twfe_fit, etwfe_fit)
```

```{r}
scored_fits <- lapply(fits, \(fit) {
  fit %>%
    filter(is.na(y0)) %>% #@$%^#@!
    group_by(method, replication) %>%
    score
}) %>% bind_rows


rlbs <- c("forest", "mex"
  , "arx_inla", "spx_inla", "twfe", "etwfe"
)
lbs <- c("basic", "mixed effect"
  , "ar(1)", "st", "twfe", "etwfe"
)

scored_fits %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) # %>%
  #gtsave("output/all.html")
```

```{r}
scored_fits_noncore <- lapply(fits, \(fit) {
  fit %>%
    filter(is.na(y0) & urb == "6.NonCore") %>%
    group_by(method, replication) %>%
    score
}) %>% bind_rows

scored_fits_noncore %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) %>%
  gtsave("output/noncore.html")
```




This assumes outcome consinstent outcome (i.e. smr= Y/E)
```{r}
#fits <- readRDS(file = paste0("data/placebo_1124.rds"))
#fits <- fits[fits$O == 0, ]
#saveRDS(fits, file = paste0("data/placebo_1124_O0.rds"))
fits <- readRDS(file = paste0("data/placebo_1124_O0.rds"))

```

```{r}
with(fits, tapply(Y, method, \(x) mean(x, trim = .01)))
with(fits, tapply(Y0.mean, method, \(x) mean(x, trim = .01)))
with(fits, tapply(Y0.b2, method, \(x) mean(x, trim = .01)))
```

correct pois and me
```{r}
fits[fits$method %in% c("me", "pois"), paste0("Y0.b", 1:400)] <-
  exp(fits[fits$method %in% c("me", "pois"), paste0("Y0.b", 1:400)])

colnames(fits)
fits[, sigma := apply(.SD, 1, sd)
     , .SDcols = paste0("Y0.b", 1:400)]
fits[, lambda := apply(.SD, 1, mean)
     , .SDcols = paste0("Y0.b", 1:400)]

with(fits, tapply(Y0.mean, method, \(x) mean(x, trim = .01)))
with(fits, tapply(Y0.sd, method, \(x) mean(x, trim = .01)))
with(fits, tapply(lambda, method, \(x) mean(x, trim = .01)))
with(fits, tapply(sigma, method, \(x) mean(x, trim = .01)))

with(fits, tapply(lambda, method, summary))
with(fits, tapply(sigma, method, summary))

table(fits$sigma == 0)


```


```{r}
#adds last layer of noise (becouse it is a prediction)
# this is used to crate CI
set.seed(0203)
sim_count <- \(x) rpois(length(x), x)
fits[, (paste0("Y0.", 1:400)) := lapply(.SD, sim_count)
     , .SDcols = paste0("Y0.b", 1:400)]


fits <- fits %>%  mutate(sigma_pred = sqrt(sigma^2 + lambda))

tapply(fits$sigma, fits$method, summary)
```



```{r}
head(fits)
table(is.na(fits$Y0))
#Dawid–Sebastiani score
#depedns only on mean and SE (or poserior SD)
#*** Becouse the true att is zero att = bias
scoring <- \(m) {
  m %>%
    mutate(
      , d = Y - y0_hat
      , ae = ae(Y, y0_hat)
      , se = se(Y, y0_hat)
      , d2 = d2(Y, y0_hat)
      , lns = log(y0_pi)
      , ds = ds(Y, y0_hat, y0_sd)
      , cvg = cvg(Y, y0_lower, y0_upper)
      , intv = intv(Y, y0_lower, y0_upper)
      , sigpred = y0_hat + y0_sd^2
    ) %>%
    reframe(
      across(c(d, ae, se, d2, ds, lns, cvg, intv, sigpred), mean)
      , se = sqrt(se)
      , sigpred = sqrt(sigpred)
      , pcor = cor(Y, y0_hat)
      , scor = cor(Y, y0_hat, method = "spearman")
    )
}

pl_tb <- fits %>%
  filter(is.na(Y0)) %>%
  group_by(method, replication) %>%
  scoring


pl_tb %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), mean)#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) #%>%
#  gtsave("output/all.html")
```


by urbanicity
```{r}
pl_tb_urb2 <- fits %>%
  group_by(o, method, replication, urb) %>%
#  filter(replication %in% 1:3) %>%
  cvg

pl_tb_urb1 <- fits %>%
  group_by(o, method, replication, urb) %>%
#  filter(replication %in% 1:3) %>%
  all_m()

pl_tb_urb <- left_join(pl_tb_urb1, pl_tb_urb2)
colnames(pl_tb_urb)

pl_tb_urb %>%
  group_by(o, method) %>%
  filter(urb == "6.NonCore") %>%
  reframe(mutate(
    across(c(dss:att_cvg), mean)
  )) %>%
  select(!o) %>%
  filter(method != "twfe") %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3)  #%>%
#  gtsave("output/ncore.html")

```

```{r}
pl_tb$method <- factor(pl_tb$method
  , levels = c("pois", "etwfe", "me", "me_inla", "tp", "sp", "st")
)
pl_tb_urb$method <- factor(pl_tb_urb$method
  , levels = c("pois", "etwfe", "me", "me_inla", "tp", "sp", "st")
)
```

```{r}

model_names <- c(
  "Pooled Poisson regression",
  "Enhanced two-way fixed-effect",
  "Mixed effect (ME)",
  "ME w/ INLA",
  "ME + temporal dependence",
  "ME + spatial dependence",
  "ME + spatiotemporal dependence"
)
levels(pl_tb$method) <- levels(pl_tb_urb$method) <- stringr::str_wrap(model_names, 20)
```

plots
```{r}
myv <- \(data, map = aes(x = method, y = cor)
  , transf = "exp"
  , ylab = "correlation"
) {
  data %>%
    filter(method != "ME w/ INLA") %>%
    ggplot(map) +
    geom_violin(aes(col =  method), show.legend = FALSE) +
    stat_summary(geom = "errorbar"
      , width = .15
      , linewidth = 1
      , fun.min = median
      , fun.max = median
    ) +
    stat_summary(geom = "errorbar"
      , width = .15
      , fun = median
      , fun.min = \(x) quantile(x, .25)
      , fun.max = \(x) quantile(x, .75)
    ) +
    scale_y_continuous(trans = transf) +
    xlab("") + ylab(ylab) +
    theme_minimal() #+
    #theme(axis.text.x = element_text(size = 12))
}
```

DSS
```{r}
tapply(pl_tb$dss, pl_tb$method, min)
myv(pl_tb, aes(x = method, y = dss), "identity", "Dawid–Sebastiani score")

png("output/dss_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = dss), "identity", "Dawid–Sebastiani score")

dev.off()

tapply(pl_tb_urb$dss, pl_tb_urb$method, min)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = dss), transf = "identity", "Dawid–Sebastiani score")

png("output/dss_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = dss), transf = "identity", "Dawid–Sebastiani score")
dev.off()
```


plot bias
```{r}

myv(pl_tb, aes(x = method, y = att^2), "log10")

png("output/bias_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = att^2), "log10")
dev.off()


pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  att^2), transf = "log10")

png("output/bias_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  att^2), transf = "log10")
dev.off()
```



plot error
```{r}
myv(pl_tb, aes(x = method, y = aes), "log10")

png("output/ae_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = aes), "log10")
dev.off()

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  aes), transf = "log10")


png("output/ae_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = aes), transf = "log10")
dev.off()
```



plot corr
```{r}
myv(pl_tb, aes(x = method, y = cor))

png("output/cor_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = cor))
dev.off()

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cor))


png("output/cor_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cor))
dev.off()
```


plot cvg
```{r}
myv(pl_tb, aes(x = method, y = cvg))

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cvg))

png("output/cvg_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = cvg))
dev.off()



png("output/cvg_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cvg))
dev.off()
```


```{r}
fits %>%
  filter(method == "re") %>%
  group_by(urb) %>%
  reframe(
    smr = mean(Y / E)
    , smr_se = mean(sqrt(smr / E))
    , y_se = mean(sqrt(smr * E))
  )

fits %>%
  filter(method == "re") %>%
  group_by(urb) %>%
  reframe(
    smr = mean(Y / E)
    , smr_se = mean(sqrt(smr / E))
    , y_se = mean(sqrt(smr * E))
  )

fits %>%
  group_by(method, urb) %>%
  filter(urb == "6.NonCore") %>%
  reframe(mean(sigma))

```