```{r}
library(data.table)
library(tidyverse)
library(parallel)
options(digitis = 3)
options(scipen = 10^5) 
options(help_type = "html")

#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)


library(gt)
```


```{r}


```

MAR
```{r}

forest_fit <- readRDS("data/forest_fit_mar.rds")
mex_fit <- readRDS("data/mex_fit_mar0.rds")
spx_fit <- readRDS("data/spx_fit_mar0.rds")
arx_fit <- readRDS("data/arx_fit_mar0.rds")
twfe_fit <- readRDS("data/twfex_fit_mar.rds")
etwfe_fit <- readRDS("data/etwfex_fit_mar.rds")
head(twfe_fit)
head(etwfe_fit)

fits <- list(forest_fit, mex_fit, arx_fit, spx_fit, twfe_fit, etwfe_fit)
```


```{r}
forest_fit <- readRDS("data/forest_fit.rds")
mex_fit <- readRDS("data/mex_fit.rds")
spx_fit <- readRDS("data/spx_fit.rds")
arx_fit <- readRDS("data/arx_fit.rds")
twfe_fit <- readRDS("data/twfe_fit.rds")
etwfe_fit <- readRDS("data/etwfe_fit.rds")

fits_mcar <- list(forest_fit, mex_fit, arx_fit, spx_fit, twfe_fit, etwfe_fit)
```

```{r}
scored_fits <- lapply(fits, \(fit) {
  fit %>%
    filter(is.na(y0)) %>% #@$%^#@!
    group_by(method, replication) %>%
    score
}) %>% bind_rows

scored_fits_noncore <- lapply(fits, \(fit) {
  fit %>%
    filter(is.na(y0) & urb == "6.NonCore") %>%
    group_by(method, replication) %>%
    score
}) %>% bind_rows


#summary(with(fits[[1]], year - start_year))

scored_fits_etime <- lapply(fits, \(fit) {
  fit %>%
    mutate(event_time = year - start_year) %>%
    filter(is.na(y0) & event_time <= 10) %>%
    group_by(method, replication, event_time) %>%
    score
}) %>% bind_rows

```

```{r}
scored_fits_mcar <- lapply(fits_mcar, \(fit) {
  fit %>%
    filter(is.na(y0)) %>% #@$%^#@!
    group_by(method, replication) %>%
    score
}) %>% bind_rows

scored_fits_noncore_mcar <- lapply(fits_mcar, \(fit) {
  fit %>%
    filter(is.na(y0) & urb == "6.NonCore") %>%
    group_by(method, replication) %>%
    score
}) %>% bind_rows
```


```{r}

rlbs <- c("forest", "mex"
  , "arx_inla", "spx_inla"
  , "twfex", "etwfex"
)
lbs <- c("basic", "mixed effect"
  , "ar(1)", "st"
  , "twfe", "etwfe"
)
scored_fits %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3)  %>%
  gtsave("output/all_mar.html")
```

```{r}
scored_fits_noncore %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) %>%
  gtsave("output/noncore_mar.html")
```

```{r}
table(scored_fits_etime$method)
scored_fits_etime %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method, event_time) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) #%>%
  #gtsave("output/noncore_mar.html")
```


```{r}
scored_fits_mcar %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3)  %>%
  gtsave("output/all_mcar.html")


scored_fits_noncore_mcar %>%
  mutate(method = factor(method, levels = rlbs, labels = lbs)) %>%
  group_by(method) %>%
  reframe(mutate(
    across(c(d:scor), \(x) mean(x))#list(m = mean, sd = sd))
  )) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) %>%
  gtsave("output/noncore_mcar.html")
```



```{r}
lbs <- c(
  "basic"
  , "mixed effect"
  , "me_inla"
  , "ar(1)"
  , "spatiotemporal"
  , "twfe"
  , "etwfe"
)
lbs <- stringr::str_wrap(lbs, 20)
```

plots
```{r}
myv <- \(data, map = aes(x = method, y = cor)
  , transf = "exp"
  , ylab = "correlation"
) {
  data %>%
    ggplot(map) +
    geom_violin(aes(col =  method), show.legend = FALSE) +
    stat_summary(geom = "errorbar"
      , width = .15
      , linewidth = 1
      , fun.min = median
      , fun.max = median
    ) +
    stat_summary(geom = "errorbar"
      , width = .15
      , fun = median
      , fun.min = \(x) quantile(x, .25)
      , fun.max = \(x) quantile(x, .75)
    ) +
    scale_y_continuous(trans = transf) +
    xlab("") + ylab(ylab) +
    theme_minimal() #+
    #theme(axis.text.x = element_text(size = 12))
}
```

```{r}
tapply(pl_tb$dss, pl_tb$method, min)

myv(scored_fits
  , aes(x = method, y = lns), "identity", "Dawid–Sebastiani score"
)
```


DSS
```{r}
tapply(pl_tb$dss, pl_tb$method, min)

myv(scored_fits
  , aes(x = method, y = dss), "identity", "Dawid–Sebastiani score"
)

png("output/dss_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = dss), "identity", "Dawid–Sebastiani score")

dev.off()

tapply(pl_tb_urb$dss, pl_tb_urb$method, min)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = dss), transf = "identity", "Dawid–Sebastiani score")

png("output/dss_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = dss), transf = "identity", "Dawid–Sebastiani score")
dev.off()
```


plot bias
```{r}

myv(pl_tb, aes(x = method, y = att^2), "log10")

png("output/bias_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = att^2), "log10")
dev.off()


pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  att^2), transf = "log10")

png("output/bias_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  att^2), transf = "log10")
dev.off()
```



plot error
```{r}
myv(pl_tb, aes(x = method, y = aes), "log10")

png("output/ae_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = aes), "log10")
dev.off()

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  aes), transf = "log10")


png("output/ae_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = aes), transf = "log10")
dev.off()
```



plot corr
```{r}
myv(pl_tb, aes(x = method, y = cor))

png("output/cor_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = cor))
dev.off()

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cor))


png("output/cor_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cor))
dev.off()
```


plot cvg
```{r}
myv(pl_tb, aes(x = method, y = cvg))

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cvg))

png("output/cvg_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = cvg))
dev.off()



png("output/cvg_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cvg))
dev.off()
```


```{r}
fits %>%
  filter(method == "re") %>%
  group_by(urb) %>%
  reframe(
    smr = mean(Y / E)
    , smr_se = mean(sqrt(smr / E))
    , y_se = mean(sqrt(smr * E))
  )

fits %>%
  filter(method == "re") %>%
  group_by(urb) %>%
  reframe(
    smr = mean(Y / E)
    , smr_se = mean(sqrt(smr / E))
    , y_se = mean(sqrt(smr * E))
  )

fits %>%
  group_by(method, urb) %>%
  filter(urb == "6.NonCore") %>%
  reframe(mean(sigma))

```