```{r}
library(data.table)
library(parallel)
#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)

dt_list <- readRDS(file = paste0("data/placebo.rds"))
```



```{r}
library(dbarts)
#data <- dt_list[[1]]
fit_bart <- function(data) {

  tmp_dat <<- data
  tmp_dat$f_id <<- factor(data$id)
  tmp_dat$f_time  <<- factor(data$time)

  b0 <- bart2(SMR ~  st
    + AIAN
    + time
    + urb
    + f_id + f_time
    , data = tmp_dat[tmp_dat$O == 1, ]
    , test = tmp_dat[tmp_dat$O == 0, ]
    , k = 1
    , n.trees = 200
    )

#  b0 <-
#    rbart_vi(SMR ~  st
#    + AIAN
#    + time
#    + urb
#    + f_id + f_time
#    + x
#    , group.by = tmp_dat$id[tmp_dat$O == 1]
#    , group.by.test = tmp_dat$id[tmp_dat$O == 0]
#    , data = tmp_dat[tmp_dat$O == 1, ]
#    , test = tmp_dat[tmp_dat$O == 0, ])


  smr0 <- matrix(NA, nrow(data), prod(dim(b0$sigma)))
  smr0[tmp_dat$O == 1, ] <- t(extract(b0, type = "ppd", sample = "train"))
  smr0[tmp_dat$O == 0, ] <- t(extract(b0, type = "ppd", sample = "test"))
  smr0    <- smr0

  tmp_dat <<- NULL
  data$SMR0 <- apply(smr0, 1, mean)
  data$method <- "bart"
  list(dt = data, post_smr0 = smr0)
}
```


BART
```{r}
# dt_tmp <- dt_list[[2]]
# new_dt <- fit_bart(dt_tmp)
# summary(new_dt)

start_time <- Sys.time()
set.seed(0203)
list_dat <- mclapply(dt_list, \(dt) {
    j <- unique(dt$tag)
    pred     <-  tryCatch(fit_bart(dt)
               ,  error = function(c) NULL)
    print(j)
    pred$dt
    }
    , mc.cores = 20
    )
end_time <- Sys.time()
end_time - start_time
bart_fits   <- rbindlist(list_dat)

saveRDS(bart_fits, file = paste0("data/p_bart_fits.rds"))
```