```{r}
library(data.table)
library(parallel)
#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)

dt_list <- readRDS(file = paste0("data/placebo.rds"))

#library(devtools)
#install_github("JonathanBradley28/CM")
library(CM)

```


```{r}
dt <- dt_list[[1]]
dim(dt)
set.seed(0203)
dt <- dt[dt$id %in% sample(unique(dt$id), 10), ]
dim(dt)


#covariate intercept-only
X <- model.matrix(~  log(E), dt)
p <- dim(X)[2]

##compute the basis function matrix
G <- model.matrix(~ -1 + factor(id), dt)


#orthogonalize G
#outG <- qr(G)
#G <- qr.Q(outG)
#orthogonalize X
outX <- qr(X)
X <- qr.Q(outX)

head(G)
head(X)
#Run the MCMC algorithm
#X An nxp matrix of covariates
#An nxr matrix of basis functions. ach column represents a basis function
#data An n dimensional vector consisting of count-valued observations

output <- GibbsPoissonMLG(Niter = 500, X, G, dt$Y)
summary(with(output
  , apply(exp(X %*% betas + G %*% etas + deltas)[, 400:500], 1, mean)
))
summary(apply(output$lambda_rep[, 400:500], 1, mean))

library(lme4)
me <-  glmer(Y ~ log(E) + (1 | id)
  , data = dt
  , family = poisson
)

summary(predict(me, type = "response", newdata = dt))

plot(predict(me, type = "response", newdata = dt)
  , apply(output$lambda_rep[, 400:500], 1, mean)
)


```

```{r}
library(lme4)

fit_me <- function(dt_tmp) {
  me <-  lmer(SMR ~ x + (- 1 + x | id) + (- 1 + x | time)
      , data = dt_tmp[dt_tmp$O == 1, ])
  dt_tmp$SMR0 <- predict(me
      , type = "response", newdata = dt_tmp)
  dt_tmp$method <- "me"
  dt_tmp
}
#dt_tmp <- dt_list[[2]]


fit_mep <- function(dt_tmp) {
  me <-  glmer.nb(Y ~ offset(log(E))
  + log(x) + (- 1 + log(x) | id) + (- 1 + log(x) | time)
      , data = dt_tmp[dt_tmp$O == 1, ]
      , family = poisson)
  dt_tmp$SMR0 <- predict(me
      , type = "response", newdata = dt_tmp) / dt_tmp$E
  dt_tmp$method <- "mep"
  dt_tmp
}




```


ME
```{r}
#dt_tmp <- dt_list[[2]]
#new_dt <- fit_me(dt_tmp)
#summary(new_dt)

start_time <- Sys.time()
list_dat <- mclapply(dt_list, \(dt) {
    j <- unique(dt$tag)
    pred     <-  tryCatch(fit_me(dt)
               ,  error = function(c) NULL)
    print(j)
    pred
    }
    , mc.cores = 20
    )
end_time <- Sys.time()
end_time - start_time
me_fits   <- rbindlist(list_dat)

saveRDS(me_fits, file = paste0("data/p_me_fits.rds"))
```


ME Poisson
```{r}
#dt_tmp <- dt_list[[2]]
#new_dt <- fit_mep(dt_tmp)
#summary(new_dt)

start_time <- Sys.time()
list_dat <- mclapply(dt_list, \(dt) {
    j <- unique(dt$tag)
    pred     <-  tryCatch(fit_mep(dt)
               ,  error = function(c) NULL)
    print(j)
    pred
    }
    , mc.cores = 20
    )
end_time <- Sys.time()
end_time - start_time
me_fits   <- rbindlist(list_dat)

saveRDS(me_fits, file = paste0("data/p_mep_fits.rds"))
```