```{r}
library(data.table)
library(parallel)
#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)

dt_list <- readRDS(file = paste0("data/placebo.rds"))
```


Mixed-effects poisson
```{r}
#df <- dt_list[[1]][opop == "youth", ]
library(lme4)
fit_mepois <- \(df) {
  fit <- glmer.nb(Y0 ~ offset(log(E)) + (time | id)
  , family = poisson
  , data = df)
  df$SMR0 <- predict(fit, df, type = "response") / df$E
  df$method <- "mepois"
  df
}

start_time <- Sys.time()
lapply(dt_list[1:2], \(dt) {
    fit <-  tryCatch(fit_mepois(dt)
            ,  error = function(c) NULL)
    fit$tag <- j
    saveRDS(fit, file = paste0("data/tmp/p_mepois_fit_", j))
    print(j)
    }
    #, mc.cores = 16
    )
end_time <- Sys.time()
end_time - start_time

list_files <- list.files("data/tmp", "p_mepois_fit_", full.names = TRUE)
list_dat   <- lapply(list_files, \(fl) readRDS(fl))
poisfits      <- rbindlist(list_dat)
saveRDS(poisfits, file = paste0("data/p_mepoisfit.rds"))

```

```{r}
afits <- readRDS(file = paste0("data/p_afit.rds"))
mepfits <- readRDS(file = paste0("data/p_mepoisfit.rds"))
stfits <- readRDS(file = paste0("data/p_stfit.rds"))
bfits <- readRDS(file = paste0("data/p_bfit.rds"))

colnames(afits)
colnames(bfits)
#fdat <- rbind(afits,mepfits, stfits,  bfits)
fdat <- rbind(afits, bfits)


fdat$ave_n <- with(fdat, ave(n, id, FUN = mean))
fdat$small <- fdat$ave_n < 3200
fdat$large <- fdat$ave_n > 23600

# I compute ans statistic in each dataset
# then measure bias and variance
table(fdat$tag)

fdat$SMR0[fdat$SMR0 < 0] <- 0

fdat[I == TRUE
  , .(att_smr = mean(SMR - SMR0))
  , .(tag, method)] [, .(bias = mean(att_smr), se = sd(att_smr)
  , mse = mean(att_smr^2), mae = mean(abs(att_smr))), keyby = .(method)]

fdat[I & small
  , .(att_smr = mean(SMR - SMR0))
  , .(tag, method)] [, .(bias = mean(att_smr), se = sd(att_smr)
  , mse = mean(att_smr^2), mae = mean(abs(att_smr))), keyby = .(method)]

```
