

```{r}
library(data.table)
library(tidyverse)
library(parallel)
options(digitis = 3)
options(scipen = 10^5) 
options(help_type = "html")

#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
set.seed(0203)
options(scipen = 10^6)

library(INLA)
library(fixest)
library(gt)
```


This assumes outcome consinstent outcome (i.e. smr= Y/E)
```{r}
#fits <- readRDS(file = paste0("data/placebo_1124.rds"))
#fits <- fits[fits$O == 0, ]
#saveRDS(fits, file = paste0("data/placebo_1124_O0.rds"))
fits <- readRDS(file = paste0("data/placebo_1124_O0.rds"))

```

```{r}
with(fits, tapply(Y, method, \(x) mean(x, trim = .01)))
with(fits, tapply(Y0.mean, method, \(x) mean(x, trim = .01)))
with(fits, tapply(Y0.b2, method, \(x) mean(x, trim = .01)))
```

correct pois and me
```{r}
fits[fits$method %in% c("me", "pois"), paste0("Y0.b", 1:400)] <-
  exp(fits[fits$method %in% c("me", "pois"), paste0("Y0.b", 1:400)])

colnames(fits)
fits[, sigma := apply(.SD, 1, sd)
     , .SDcols = paste0("Y0.b", 1:400)]
fits[, lambda := apply(.SD, 1, mean)
     , .SDcols = paste0("Y0.b", 1:400)]

with(fits, tapply(Y0.mean, method, \(x) mean(x, trim = .01)))
with(fits, tapply(Y0.sd, method, \(x) mean(x, trim = .01)))
with(fits, tapply(lambda, method, \(x) mean(x, trim = .01)))
with(fits, tapply(sigma, method, \(x) mean(x, trim = .01)))

with(fits, tapply(lambda, method, summary))
with(fits, tapply(sigma, method, summary))

table(fits$sigma == 0)


```


```{r}
#adds last layer of noise (becouse it is a prediction)
# this is used to crate CI
set.seed(0203)
sim_count <- \(x) rpois(length(x), x)
fits[, (paste0("Y0.", 1:400)) := lapply(.SD, sim_count)
     , .SDcols = paste0("Y0.b", 1:400)]


fits <- fits %>%  mutate(sigma_pred = sqrt(sigma^2 + lambda))

tapply(fits$sigma, fits$method, summary)
```



```{r}
head(fits)
#Dawid–Sebastiani score
#depedns only on mean and SE (or poserior SD)
#*** Becouse the true att is zero att = bias
all_m <- \(m) {
  m %>%
    reframe(
      #Dawid–Sebastiani score
      dss = mean(((Y - lambda) / sigma_pred) ^ 2 + 2 * log(sigma_pred))
      , att = mean((Y - lambda))
      , ses = mean((Y - lambda)^2) #square error
      , aes = mean(abs((Y - lambda)))  #abs error
      #, sse_smr = mean(mean((SMR - SMR0.mean) ^ 2)) #square error smr
      #, cvg = mean(Y > Y0.lw & Y < Y0.up)
      , cor = cor(Y, lambda)
      , cork = cor(rank(Y), rank(lambda))
      , sig = sqrt(mean(sigma_pred^2))
      #, att_se = sqrt(ses / n())
      #, att_lw = att - 2 * att_se
      #, att_up = att + 2 * att_se
      #, att_cvg = att > att_lw & att < att_up
      #, rss = mean((Y - lambda)^2 / lambda)
    )
}



cvg <- \(m) {
  m %>%
    mutate(across(Y0.1:Y0.400, \(x) Y - x)) %>%
    reframe(across(Y0.1:Y0.400, mean)) %>% #a single value per replicaiton
    rowwise %>%
    mutate(
      , att_lw = quantile(c_across(Y0.1:Y0.400), .025)
      , att_up = quantile(c_across(Y0.1:Y0.400), .975)
      , att_cvg = 0 > att_lw & 0 < att_up
    ) %>%
    select(!c(Y0.1:Y0.400, att_lw, att_up))
}




pl_tb2 <- fits %>%
  group_by(o, method, replication) %>%
#  filter(replication %in% 1:3) %>%
  cvg


pl_tb1 <- fits %>%
  group_by(o, method, replication) %>%
#  filter(replication %in% 1:3) %>%
  all_m()

pl_tb <- left_join(pl_tb1, pl_tb2)
summary(pl_tb)


pl_tb %>%
  group_by(o, method) %>%
  reframe(mutate(
    across(c(dss:att_cvg), mean)#list(m = mean, sd = sd))
  )) %>%
  select(!o) %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3) #%>%
#  gtsave("output/all.html")
```


by urbanicity
```{r}
pl_tb_urb2 <- fits %>%
  group_by(o, method, replication, urb) %>%
#  filter(replication %in% 1:3) %>%
  cvg

pl_tb_urb1 <- fits %>%
  group_by(o, method, replication, urb) %>%
#  filter(replication %in% 1:3) %>%
  all_m()

pl_tb_urb <- left_join(pl_tb_urb1, pl_tb_urb2)
colnames(pl_tb_urb)

pl_tb_urb %>%
  group_by(o, method) %>%
  filter(urb == "6.NonCore") %>%
  reframe(mutate(
    across(c(dss:att_cvg), mean)
  )) %>%
  select(!o) %>%
  filter(method != "twfe") %>%
  gt %>%
  fmt_number(columns = where(is.numeric), decimals = 3)  #%>%
#  gtsave("output/ncore.html")

```

```{r}
pl_tb$method <- factor(pl_tb$method
  , levels = c("pois", "etwfe", "me", "me_inla", "tp", "sp", "st")
)
pl_tb_urb$method <- factor(pl_tb_urb$method
  , levels = c("pois", "etwfe", "me", "me_inla", "tp", "sp", "st")
)
```

```{r}

model_names <- c(
  "Pooled Poisson regression",
  "Enhanced two-way fixed-effect",
  "Mixed effect (ME)",
  "ME w/ INLA",
  "ME + temporal dependence",
  "ME + spatial dependence",
  "ME + spatiotemporal dependence"
)
levels(pl_tb$method) <- levels(pl_tb_urb$method) <- stringr::str_wrap(model_names, 20)
```

plots
```{r}
myv <- \(data, map = aes(x = method, y = cor)
  , transf = "exp"
  , ylab = "correlation"
) {
  data %>%
    filter(method != "ME w/ INLA") %>%
    ggplot(map) +
    geom_violin(aes(col =  method), show.legend = FALSE) +
    stat_summary(geom = "errorbar"
      , width = .15
      , linewidth = 1
      , fun.min = median
      , fun.max = median
    ) +
    stat_summary(geom = "errorbar"
      , width = .15
      , fun = median
      , fun.min = \(x) quantile(x, .25)
      , fun.max = \(x) quantile(x, .75)
    ) +
    scale_y_continuous(trans = transf) +
    xlab("") + ylab(ylab) +
    theme_minimal() #+
    #theme(axis.text.x = element_text(size = 12))
}
```

DSS
```{r}
tapply(pl_tb$dss, pl_tb$method, min)
myv(pl_tb, aes(x = method, y = dss), "identity", "Dawid–Sebastiani score")

png("output/dss_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = dss), "identity", "Dawid–Sebastiani score")

dev.off()

tapply(pl_tb_urb$dss, pl_tb_urb$method, min)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = dss), transf = "identity", "Dawid–Sebastiani score")

png("output/dss_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = dss), transf = "identity", "Dawid–Sebastiani score")
dev.off()
```


plot bias
```{r}

myv(pl_tb, aes(x = method, y = att^2), "log10")

png("output/bias_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = att^2), "log10")
dev.off()


pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  att^2), transf = "log10")

png("output/bias_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  att^2), transf = "log10")
dev.off()
```



plot error
```{r}
myv(pl_tb, aes(x = method, y = aes), "log10")

png("output/ae_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = aes), "log10")
dev.off()

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y =  aes), transf = "log10")


png("output/ae_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = aes), transf = "log10")
dev.off()
```



plot corr
```{r}
myv(pl_tb, aes(x = method, y = cor))

png("output/cor_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = cor))
dev.off()

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cor))


png("output/cor_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cor))
dev.off()
```


plot cvg
```{r}
myv(pl_tb, aes(x = method, y = cvg))

pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cvg))

png("output/cvg_all.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
myv(pl_tb, aes(x = method, y = cvg))
dev.off()



png("output/cvg_ncore.png"
  , width = 480 * 5, heigh = 480 * 3, res = 300)
pl_tb_urb %>%
  filter(urb == "6.NonCore") %>%
  myv(aes(x = method, y = cvg))
dev.off()
```


```{r}
fits %>%
  filter(method == "re") %>%
  group_by(urb) %>%
  reframe(
    smr = mean(Y / E)
    , smr_se = mean(sqrt(smr / E))
    , y_se = mean(sqrt(smr * E))
  )

fits %>%
  filter(method == "re") %>%
  group_by(urb) %>%
  reframe(
    smr = mean(Y / E)
    , smr_se = mean(sqrt(smr / E))
    , y_se = mean(sqrt(smr * E))
  )

fits %>%
  group_by(method, urb) %>%
  filter(urb == "6.NonCore") %>%
  reframe(mean(sigma))

```