```{r}
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")

library(parallel)
library(tidyverse)
library(rpart)
library(collapse)
library(fwb)
library(data.table)

#load R functions
sapply(list.files("R/", ".r", full.names = TRUE), source)
load("data/W")
rownames(W) <- NULL
```

Select data
(compact is created in 3.0, basically a subset)
```{r}
dt <-  readRDS("data/compact_dt.rds")
dt <- as.data.table(dt, key = c("i", "year"))
dt[, urb := ordered(urb
    , labels = c("Large Core Metro"
      , "Large Fringe Metro", "Medium Metro", "Small Metro", "Micro", "NonCore"
    )
  )
]
dt[, urb2 := oredered(
  ifelse(urb == "NonCore", "NonCore", "All other counties")
)]
table(dt$urb2)
```

```{r}
#dt0 <- dt
graph <- W_est(dt, W)
dt  <- dt |> impute_inla(fit_fun = fit_spt, nb = 2000)

```

CUMMULATIVE
```{r}
dt_cum <- dt[is.na(y0), ]
# Get all y0_post columns
y0_post_cols <- grep("y0_post_", names(dt), value = TRUE)

# Create cumulative sums by i, ordered by event_time
dt_cum[order(i, event_time)
       , c("y", "y0_hat", y0_post_cols) := lapply(.SD, cumsum)
       , by = i  # Group by both i and replication
       , .SDcols = c("y", "y0_hat", y0_post_cols)]

head(dt_cum[, .(y0_hat)])
head(dt_cum[, ..y0_post_cols])

ggplot(dt_cum[event_time <= 6, ], aes(x = factor(event_time)
  , y = y - rowMeans(dt_cum[event_time <= 6, ..y0_post_cols])
)) +
  geom_boxplot(col = "red", alpha = .2) +
  geom_boxplot(data = dt_cum[event_time <= 6, ]
    , aes(x = factor(event_time), y = y - y0_hat), col = "blue", alpha = .2
  )

```
EXTRA VAR
```{r}
set.seed(0203)
y0_cols <- c("y0_hat", y0_post_cols)
pois_matrix <- mrpois(dt_cum[, ..y0_cols])
dt_cum[, (y0_cols) := as.data.frame(pois_matrix)]


head(dt_cum[, .(y0_hat)])
head(dt_cum[, ..y0_post_cols])

ggplot(dt_cum[event_time <= 6, ], aes(x = factor(event_time)
  , y = y - rowMeans(dt_cum[event_time <= 6, ..y0_post_cols])
)) +
  geom_boxplot(col = "red", alpha = .2) +
  geom_boxplot(data = dt_cum[event_time <= 6, ]
    , aes(x = factor(event_time), y = y - y0_hat), col = "blue", alpha = .2
  )

```
DELTA
```{r}
d_cols <- paste0("d_", y0_cols)
dt_cum[, (d_cols) :=
         lapply(.SD, \(col) y - col),
       .SDcols = y0_cols]

dt[, (d_cols) :=
     lapply(.SD, \(col) y - col),
   .SDcols = y0_cols]

```


SUMMARY
```{r}
tb <- dt_cum[#event_time %in% c(0, 2, 6)
  , lapply(.SD, mean)
  , by = .(urb2, event_time)
  , .SD = d_cols
][, {
  # Convert diff columns to matrix
  mat <- as.matrix(.SD)
  # Calculate quantiles by row
  data.table(
    diff_y0_hat = mat[, 1]
    , q025 = fquantile(mat[, -1], 0.025)
    , q975 = fquantile(mat[, -1], 0.975)
  )
} , by = .(urb2, event_time), .SDcols = d_cols
]

tb

ggplot(tb[event_time <= 6,]
  , aes(x = event_time
    , y = diff_y0_hat, ymin = q025, ymax = q975
  )
) +
  geom_line() + geom_ribbon(alpha = .2) +
  theme_minimal() +
  facet_wrap(~urb2, ncol = 1) +
  theme(legend.position = "none")
```


Application
```{r}
eff <- \(.dt, include_mean = FALSE) {
  # Get column names from input data (.dt not dt)
  y0_post_cols <- grep("y0_post_", names(.dt), value = TRUE)
  cum_y0_post_cols <- paste0("cum_", c("y", "y0_hat", y0_post_cols))
  d_post_cols <- paste0("diff_", c("y0_hat", y0_post_cols))

  # Create a copy to work with
  result <- copy(.dt)

  # STEP 1: Calculate the mrpois results outside the := operation
  matrix_cols <- c("y0_hat", y0_post_cols)
  pois_matrix <- mrpois(as.matrix(result[, ..matrix_cols]))

  # STEP 2: Assign the results back to the data.table
  result[, (matrix_cols) := as.data.frame(pois_matrix)]

  # Rest of your function remains the same
  result[order(i, event_time),
         (cum_y0_post_cols) := lapply(.SD, cumsum),
         by = .(i),
         .SDcols = c("y", "y0_hat", y0_post_cols)]

  result[, (d_post_cols) :=
           lapply(.SD, function(col) get("cum_y") - col),
         .SDcols = cum_y0_post_cols[-1]]

  d_post <- result[, ..d_post_cols] %>% as.matrix
  d_post <- d_post[, -1] # remove first column (y0_hat)

  # Calculate all values first
  d_hat_val <- if (include_mean) rowMeans(d_post) else NULL
  d_sd_val <- fsd(t(d_post))

  # Calculate bounds
  bounds <- fquantile(t(d_post), c(.025, .975)) %>% t

  if (include_mean) result[, d_hat := d_hat_val]
  result[, `:=`(
    y0_sd = d_sd_val,
    y0_lower = bounds[, 1],
    y0_upper = bounds[, 2]
  )]

  return(result)
}
```

OVERALL
```{r}
dt1 <- readRDS("data/forest_fit_case.rds")
dt1 <- readRDS("data/forest_fit_case_exvar_false.rds")
summary(dt1$y0_hat)
dt1 <- dt1 %>% post_summary(include_mean = TRUE)

```
same conclusion, but extra var decreased uncertainty 
we need to estiamte if coverage is OK
```{r}
dt1 %>% filter(is.na(y0)) %>% score %>% summ_score
dt1 %>% filter(is.na(y0) & urb == "6.NonCore") %>% score %>% summ_score

dpt <- dt1 %>% filter(is.na(y0)) %>% agg(urb) %>% eval %>% score %>%
  select(y, y0_hat, y0_lower, y0_upper, d)
dpt

ggplot(dpt
  , aes(y = levels(dt$urb)
    , x = y0_hat / y, xmin = y0_lower / y, xmax = y0_upper / y
    , col = levels(dt$urb)
  )
) +
  geom_point() + geom_pointrange() +
  geom_vline(xintercept = 1, linetype = 2) +
  theme_minimal() +
  scale_y_discrete(limits = rev) +
  theme(legend.position = "none")
```

FIVE YEARS
```{r}
dpt <- dt1 %>% filter(is.na(y0) & event_time <= 5) %>%
  agg(urb) %>% eval %>% score %>%
  select(y, y0_hat, y0_lower, y0_upper, d)
dpt

ggplot(dpt
  , aes(y = levels(dt$urb)
    , x = y0_hat / y, xmin = y0_lower / y, xmax = y0_upper / y
    , col = levels(dt$urb)
  )
) +
  geom_point() + geom_pointrange() +
  geom_vline(xintercept = 1, linetype = 2) +
  theme_minimal() +
  scale_y_discrete(limits = rev) +
  theme(legend.position = "none")
```

```{r}
ggplot(dt1, aes(x = event_time, y = sqrt(y / y0_hat)# / n * 10^5
  , group = i, col = factor(i)
)) +
  geom_line(alpha = .2) +
  guides(colour = "none") +
  facet_grid(urb ~ ., scales = "free_y") +
  theme_minimal()
```

```{r}
rpoism <- \(m) {
  r <- dim(m)
  rpois(prod(r), m) %>% matrix(r)
}

dt1 %>%
  filter(is.na(y0) & event_time <= 5 & urb == "6.NonCore") %>%
  with(y0_post) %>%
  rpoism  %>%
  apply(2, sum) %>%
  quantile(c(0.025, 0.975))
dt1 %>%
  filter(is.na(y0) & event_time <= 5 & urb == "6.NonCore") %>%
  reframe(sum(Y))
```



```{r}

n <- 10^5
eta <- exp(rnorm(n))
x <- rpois(n, eta)
mean(x)
sd(x)
quantile(x, c(0.025, 0.975))

eta_mean <- mean(log(eta))
eta_sd <- sd(log(eta))
ci_poilog(eta_mean, eta_sd)


m <- matrix((0:5)^4, 2, 3)
m
rpoism(m)

dt1 %>%
  filter(is.na(y0) & event_time <= 5 & urb == "1.LCMetro") %>%
  with(y0_post) %>%
  rpoism  %>%
  apply(2, sum) %>%
  quantile(c(0.025, 0.975))

dt1 %>%
  filter(is.na(y0) & event_time <= 5 & urb == "1.LCMetro") %>%
  reframe(sum(Y))



lapply(levels(dt1$urb), \(j) {
  dt1 %>%
    filter(is.na(y0) & urb == j & event_time <= 5) %>%
    with(., (replicate(200, Y) / y0_post - 1)) %>%
    apply(2, mean) %>%
    quantile(c(0.025, 0.975))
})

```


```{r}

dt1 <- dt1 %>% mutate(horizon =  case_when(
  event_time < 0 ~ "before"
  , 0 <= event_time & event_time <= 3 ~ "0-3"
  , 4 <= event_time & event_time <= 8 ~ "4-7"
  , 9 <= event_time ~ "9 +"
))

dt1 %>%
  filter(is.na(y0)) %>%
  group_by(urb) %>%
  reframe(
    tau = sum(Y - y0_hat) / sum(n) * 10^5
    , tau2 = mean((Y - y0_hat) / n) * 10^5
    , tau3 = mean((Y - y0_hat))
    , rtau = sum(Y) / sum(y0_hat) - 1
  )

with(filter(dt1, is.na(y0) & urb == "1.LCMetro"),
  apply(y0_post, 2, \(y0h) {
    (sum(Y) / sum(y0h)) - 1
  }) %>% quantile(c(0.025, 0.975))
)



with(filter(dt1, is.na(y0) & urb == "1.LCMetro"),
  apply(y0_post, 2, \(y0h) {
    (sum(Y) / sum(y0h)) - 1
  }) %>% quantile(c(0.025, 0.975))
)

dt1$event_time <- dt1$year - dt1$start_year
sapply(levels(dt1$urb), \(j) {
  with(filter(dt1, is.na(y0) & urb == j & event_time <= 5),
    apply(y0_post, 2, \(y0h) {
      (sum(Y) / sum(y0h)) - 1
    }) %>% quantile(c(0.025, 0.975))
  )
})

```


```{r}
set.seed(0203)
fm <- formula(y0 ~ 1 | start_year + year)
dt2 <- dt %>%
  add_avg %>%
  impute_forest(200, k = 1,  min_bucket = 7, max_depth = 30) %>%
  fit_fe(20)


saveRDS(dt1, "data/twfe_case.rds")
```

```{r}
dt2 %>%
  filter(is.na(y0)) %>%
  group_by(urb) %>%
  reframe(
    tau = sum(Y - y0_hat) / sum(n) * 10^5
    , tau2 = mean((Y - y0_hat) / n) * 10^5
    , tau3 = mean((Y - y0_hat))
    , rtau = sum(Y) / sum(y0_hat) - 1
  )

dt2$event_time <- dt2$year - dt2$start_year
sapply(levels(dt2$urb), \(j) {
  with(filter(dt2, is.na(y0) & urb == j & event_time <= 5),
    apply(y0_post, 2, \(y0h) {
      (sum(Y) / sum(y0h)) - 1
    }) %>% quantile(c(0.025, 0.975))
  )
})


```
Something strange.


```{r}
tapply(dt1$start_year, dt1$urb, median)
cor(rank(dt1$start_year), dt1$n)


```

